# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  border: single
  showFileTree: false # Just the list the files changed
  showCommandLog: false
  commitHashLength: 0 # Hide SHAs in commit log
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 3
  enlargedSideViewLocation: top
  theme:
    activeBorderColor:
      - '#8aadf4'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
    cherryPickedCommitBgColor:
      - '#494d64'
    cherryPickedCommitFgColor:
      - '#8aadf4'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#cad3f5'
    searchingActiveBorderColor:
      - '#eed49f'
  authorColors:
    '*': '#b7bdf8'
git:
  pagers:
    - # externalDiffCommand: difft --color=always --display=inline --syntax-highlight=on --tab-width=2
      colorArg: always
      pager: delta --color-only --dark --paging=never --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  overrideGpg: true
